spring:
  application:
    name: OFFICE-SERVICE
  rabbitmq:
    host: rabbitmq
    port: '5672'
    username: guest
    password: guest
  boot:
    message: Office service is UP!
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/moneron
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: '1.0'

logging:
  level:
    org:
      springframework:
        web: ERROR
#  pattern:
#    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
