spring:
  application:
    name: EXPENSE-TRACKER
  rabbitmq:
    host: localhost
    port: "5672"
    username: guest
    password: guest
  boot:
    message: Expense tracker is UP!
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/moneron
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: "1.0"

logging:
  level:
    org:
      springframework:
        web: ERROR
